conditional git push builder file

diff --git a/.github/workflows/builder.yml b/.github/workflows/builder.yml
--- a/.github/workflows/builder.yml
+++ b/.github/workflows/builder.yml
@@ -25,5 +25,14 @@ jobs:
           git config --local user.name "Ali Shahidi"
           current_date=$(date +"%Y-%m-%d")
           git add .
-          git commit -m "Builder running at $current_date from workflow"
-          git push
+          set +e  # Grep succeeds with nonzero exit codes to show results.
+          git status | grep modified
+          if [ $? -eq 0 ]
+          then
+              set -e
+              git commit -m "Builder running at $current_date from workflow"
+              git push
+          else
+              set -e
+              echo "No changes since last run"
+          fi
